use_default_settings: true

general:
  instance_name: "ShopEase SearXNG"

server:
  limiter: false
  image_proxy: false

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en-US"
  formats:
    - html
    - json

redis:
  url: redis://redis:6379/0

engines:
  - name: duckduckgo
    disabled: false
  - name: bing
    disabled: false
  - name: startpage
    disabled: false
